version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ../dreamteam_project/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend